openapi: 3.0.0
info:
  title: emailnotificationservice - Notification API JavaSp
  description: API for sending emails through Azure Communication Services
  version: '1.0'
servers:
  - url: "{server}:{port}/notifications"
tags:
  - name: Email
    description: Operations related to sending emails
paths:
  /send-email:
    post:
      tags:
        - Email
      summary: Send an email
      description: Sends an email to the specified recipient with a subject and body.
      requestBody:
        description: Email request details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailRequest'
        required: true
      responses:
        '200':
          description: Email sent successfully
          content:
            text/plain:
              schema:
                type: string
                example: email sent successfully
        '400':
          description: Bad request when the request body is not correctly formed
        '500':
          description: Internal server error
components:
  schemas:
    EmailRequest:
      required:
        - body
        - recipient
        - subject
      type: object
      properties:
        body:
          type: string
          description: The plain text email body
          example: This is a test email.
        recipient:
          type: string
          description: The recipient's email address
          example: jane.doe@example.com
        subject:
          type: string
          description: The email subject
          example: Hello World
      description: Email request details
  
